CREATE TABLE SYSTEM.chat_sessions (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_name VARCHAR2(150) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE chat_history (
    message_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id NUMBER NOT NULL,
    role VARCHAR2(15) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_session FOREIGN KEY (session_id) REFERENCES chat_sessions(session_id) ON DELETE CASCADE,
    CONSTRAINT chk_role_val CHECK (role IN ('user', 'assistant', 'system'))
);

CREATE INDEX idx_session_timeline ON chat_history(session_id, created_at DESC);